version: '3.5'

services:
  postgres-gateway:
    container_name: postgres-gateway
    image: postgres
    environment:
      POSTGRES_DB: federations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      PGDATA: /data/postgres-gateway
    volumes:
      - postgres-gateway:/data/postgres-gateway
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    postgres-gateway: